# Generated by Django 5.2.8 on 2025-12-06 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998123456789'. Up to 15 digits allowed.", regex='^\\+998\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998123456789'. Up to 15 digits allowed.", regex='^\\+998\\d{9}$')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('open', 'open'), ('close', 'close')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('work', 'work'), ('close', 'close')], max_length=20, null=True)),
                ('delivery_time', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurants')),
            ],
            options={
                'verbose_name': 'Restaurant Branch',
                'verbose_name_plural': 'Restaurant Branches',
                'db_table': 'restaurant_branches',
                'ordering': ['name', 'restaurant', 'state', 'status'],
            },
        ),
    ]
