# Generated by Django 5.2.8 on 2025-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default_user.png', null=True, upload_to='profile_photos/'),
        ),
    ]
