# Generated by Django 5.2.8 on 2025-11-21 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_customuser_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(auto_created=True, unique=True)),
                ('device_ip', models.CharField(blank=True, max_length=30, null=True)),
                ('device_hardware', models.CharField(max_length=50)),
                ('device_name', models.CharField()),
                ('location_city', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
