# Generated by Django 5.2.8 on 2025-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-last_online'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='last_used',
            new_name='last_online',
        ),
        migrations.AddField(
            model_name='device',
            name='access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
