# Generated by Django 5.2.8 on 2025-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='profile_photos/'),
        ),
    ]
