# Generated by Django 5.2.8 on 2025-11-27 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_customuser_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True)),
                ('name', models.CharField(blank=True, help_text='Manzil nomi (Uy, Ish, ...)', max_length=100, null=True)),
                ('address', models.CharField(help_text="To'liq manzil", max_length=255)),
                ('apartment', models.CharField(blank=True, help_text='Kvartira raqami', max_length=50, null=True)),
                ('entrance', models.CharField(blank=True, help_text='Kirish', max_length=50, null=True)),
                ('floor', models.CharField(blank=True, help_text='Qavat', max_length=50, null=True)),
                ('door_phone', models.CharField(blank=True, help_text='Domofon kodi', max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, help_text="Qo'shimcha ko'rsatmalar", null=True)),
                ('default', models.BooleanField(default=False, help_text='Asosiy manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'users_address',
                'ordering': ['-default', '-created_at'],
            },
        ),
    ]
