# Generated by Django 5.2.8 on 2025-11-30 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0011_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Karta nomi (Mening kartam, Ish kartasi...)', max_length=100, null=True)),
                ('card_number', models.CharField(help_text='Karta raqami (masalan: 8600 1234 5678 9012)', max_length=19)),
                ('card_name', models.CharField(help_text='Karta egasining ismi', max_length=100)),
                ('card_expiry_date', models.CharField(help_text='Amal qilish muddati (MM/YY)', max_length=5)),
                ('phone_number', models.CharField(blank=True, help_text='Telefon raqami', max_length=20, null=True)),
                ('default', models.BooleanField(default=False, help_text='Asosiy karta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'users_card',
                'ordering': ['-default', '-created_at'],
            },
        ),
    ]
