# Generated by Django 5.2.8 on 2025-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='UzCard', help_text='Karta egasining ismi', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(help_text='Karta raqami (masalan: 8600 1234 5678 9012)', max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Telefon raqami', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
