from .custom_user import *
from .device import *
from .login import *
from .profile_photo import *
from .register import *
from .send_activation import *
from .verify_activation import *
from .forgot_password import *
from .reset_password import *